[package]
name = "metashovel"
version = "0.1.0"
authors = ["Jon Moroney <darakian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
reqwest = { version = "0.10.0", features = ["blocking"] }
